name: Build Windows EXE and Attach to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          working-directory: ${{ github.workspace }}
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller (with icon and resources)
        working-directory: ${{ github.workspace }}
        run: |
          pyinstaller --onefile --add-data "resources;resources" --name "P4 Cache Cleaner" p4_cleaner_advanced.py

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}